version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Build Images
          command: |
            sh scripts/build.sh $CIRCLE_BRANCH
      - run:
          name: Bootstrap tests
          command: |
            docker swarm init
            docker network create --attachable --driver overlay redis
            sh scripts/bootstrap.sh $CIRCLE_BRANCH
      - run:
          name: Test init
          command: |
            sh scripts/test_init.sh
      - run:
          name: Test Scale
          command: |
            sh scripts/test_scale.sh $CIRCLE_BRANCH
      - run:
          name: Teardown
          command: |
            sh scripts/cleanup.sh $CIRCLE_BRANCH
            docker network rm redis
          when: always
      - deploy:
          name: Push to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] && [ -z "$CIRCLE_PULL_REQUEST" ]; then
              docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
              look_redis_v=$(grep "FROM redis" redis-look/Dockerfile | cut -d ":" -f2 | cut -d "-" -f1)
              sentinel_redis_v=$(grep "FROM redis" redis-sentinel/Dockerfile | cut -d ":" -f2 | cut -d "-" -f1)
              utils_redis_v=$(grep "FROM redis" redis-utils/Dockerfile | cut -d ":" -f2 | cut -d "-" -f1)

              look_image_v=$(grep "LABEL version" redis-look/Dockerfile | cut -d "=" -f2 | tr -d '"')
              sentinel_image_v=$(grep "LABEL version" redis-sentinel/Dockerfile | cut -d "=" -f2 | tr -d '"')
              utils_image_v=$(grep "LABEL version" redis-utils/Dockerfile | cut -d "=" -f2 | tr -d '"')

              LOOK_VERSION="${look_image_v}-redis-${look_redis_v}"
              SENTINEL_VERSION="${sentinel_image_v}-redis-${sentinel_redis_v}"
              UTILS_VERSION="${utils_image_v}-redis-${utils_redis_v}"

              docker tag thomasjpfan/redis-look:$CIRCLE_BRANCH \
                thomasjpfan/redis-look:$LOOK_VERSION
              docker tag thomasjpfan/redis-sentinel:$CIRCLE_BRANCH \
                thomasjpfan/redis-sentinel:$SENTINEL_VERSION
              docker tag thomasjpfan/redis-utils:$CIRCLE_BRANCH \
                thomasjpfan/redis-utils:$UTILS_VERSION

              docker push thomasjpfan/redis-look:$LOOK_VERSION
              docker push thomasjpfan/redis-sentinel:$SENTINEL_VERSION
              docker push thomasjpfan/redis-utils:$UTILS_VERSION

              docker tag thomasjpfan/redis-look:$CIRCLE_BRANCH \
                thomasjpfan/redis-look:latest
              docker tag thomasjpfan/redis-sentinel:$CIRCLE_BRANCH \
                thomasjpfan/redis-sentinel:latest
              docker tag thomasjpfan/redis-utils:$CIRCLE_BRANCH \
                thomasjpfan/redis-utils:latest

              docker push thomasjpfan/redis-look:latest
              docker push thomasjpfan/redis-sentinel:latest
              docker push thomasjpfan/redis-utils:latest
            fi
