version: '3'

services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    hostname: elasticsearch1
    volumes:
      - elasticsearch1-data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=elasticsearch-cluster
      - "discovery.zen.ping.unicast.hosts=tasks.elasticsearch1"
      - "network.host=0.0.0.0"
      - "node.max_local_storage_nodes=2"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elasticsearch_distributed
    deploy:
      replicas: 3
      restart_policy:
        delay: 30s
        max_attempts: 10
        window: 120s
volumes:
  elasticsearch1-data:

networks:
  elasticsearch_distributed:
    driver: overlay